stages:
  - build

build:
  stage: build
  image: golang
  before_script:
    - (go get oogle.golang.org/api/photoslibrary/v1 && cd $GOPATH/src/google.golang.org/api/photoslibrary/v1 && git apply $CI_PROJECT_DIR/patches/media-item-filename.patch)
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
  script:
    - cd cmd/sync
    - ./build.sh

  artifacts:
    paths:
    - "builds/*"